root = "."
tmp_dir = "_build"

[build]
  bin = "./_build/main"
  cmd = "templ generate && go build -o ./_build/main ./cmd/app/main.go"
  delay = 1000
  exclude_dir = ["_build", "vendor", "assets/node_modules", "_data"]
  exclude_file = []
  exclude_regex = [".*_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "templ", "html", "css", "js", "ts"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false
