# fly.toml app configuration file generated for dfc on 2024-01-24T21:38:53Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dfc"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[mounts]
  source = "myapp_data"
  destination = "/data"
  processes= ["app"]
